export enum TypeMaintenance {
  COOPERATIVE = 'COOPERATIVE',

  SOCIETE = 'SOCIETE',

  INGENIERIE = 'INGENIERIE',

  ADMINISTRATION = 'ADMINISTRATION',

  DIRECTION = 'DIRECTION',

  TECHNIQUE = 'TECHNIQUE',

  RESEAU = 'RESEAU',

  RELATIONS = 'RELATIONS',
}
